# Generated by Django 5.2.17 on 2026-09-15 04:33

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('weight_kg', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Peso (kg)')),
                ('height_cm', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Estatura (cm)')),
                ('systolic_bp', models.IntegerField(verbose_name='Presión Sistólica (mmHg)')),
                ('diastolic_bp', models.IntegerField(verbose_name='Presión Diastólica (mmHg)')),
                ('heart_rate', models.IntegerField(verbose_name='Frecuencia Cardíaca (BPM)')),
                ('blood_glucose', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Glucosa en Sangre (mg/dL)')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notas de Consulta / Síntomas')),
                ('recorded_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Registro')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Registro de Salud',
                'verbose_name_plural': 'Registros de Salud',
                'ordering': ['-recorded_at'],
            },
        ),
    ]
